module.exports = {
    rules: {
        'array-bracket-spacing': 2,
        'brace-style': [2, 'stroustrup', { allowSingleLine: true }],
        'block-scoped-var': 'error',
        'comma-dangle': [2, 'never'],
        'comma-spacing': 2,
        'comma-style': 2,
        'curly': [0, 'multi-line'],
        'dot-notation': 2,
        'eol-last': 2,
        'eqeqeq': 2,
        'indent': [2, 4],
        'key-spacing': 2,
        'keyword-spacing': 2,
        'new-cap': 2,
        'no-console': 1,
        'no-alert': 'error',
        'no-continue': 2,
        'no-empty-function': 'off',
        // no extra semi's
        'no-extra-semi': 2,
        'no-eval': 2,
        'no-implied-eval': 2,
        // prevent irregular white space
        'no-irregular-whitespace': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multi-str': 2,
        'no-new-func': 'error',
        'no-plusplus': 2,
        'no-sequences': 2,
        'no-trailing-spaces': 2,
        'no-undef': 2,
        'no-underscore-dangle': 2,
        'no-with': 2,
        'one-var': ['error', { uninitialized: 'always', initialized: 'never' }],
        'semi': 2,
        'semi-spacing': 2,
        'space-before-blocks': 2,
        'space-before-function-paren': [2, { 'anonymous': 'always', 'named': 'never' }],
        'space-in-parens': 2,
        'space-infix-ops': 2,
        'space-unary-ops': 2,
        'wrap-iife': 2
    }
};
